//! Persistent storage of key pairs for DIDs managed by `didtool`.
//!
//! Each DID gets its own subdirectory under a configurable root (default `~/.didtool/keys`).
//! The subdirectory name is the first 12 hex characters of the BLAKE3 hash of the DID string,
//! which serves as a short, stable handle that users can type on the command line instead of
//! the full DID.
//!
//! Within each DID subdirectory, key pairs are stored in numbered snapshot directories
//! (`0001/`, `0002/`, …) whose number matches the sequence number that prefixes the
//! `versionId` of the corresponding DID log entry. Each snapshot is a full set of all three
//! active key pairs — not a delta — so the latest snapshot always contains the complete
//! current key material without requiring history traversal. Older snapshots are retained for
//! verifying past signatures.
//!
//! Keys are never inserted directly through this module's public API. They are created as a
//! side effect of DID operations (`generate`/`commit`, `update`) and can only be read or
//! exported afterwards. See `key-store.md` for the full specification.

use std::path::{Path, PathBuf};

use swiyu_core::did::DID;
use thiserror::Error;
use tracing::debug;

use ed25519_dalek::VerifyingKey as Ed25519VerifyingKey;
use p256::ecdsa::VerifyingKey as EcdsaVerifyingKey;
use zeroize::ZeroizeOnDrop;

use crate::crypto::{
    CryptoError, generate_ecdsa_key_pair, generate_eddsa_key_pair, write_private_key_ecdsa,
    write_private_key_eddsa, write_public_key_ecdsa, write_public_key_eddsa,
};

#[derive(Debug, Error)]
pub enum KeyStoreError {
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),
    #[error("entry '{0}' already exists")]
    AlreadyExists(String),
    #[error("entry '{0}' not found")]
    NotFound(String),
    /// The subdirectory exists but `did.txt` contains a different DID — hash collision or
    /// corruption.
    #[error("entry '{0}': did.txt contains a different DID")]
    Mismatch(String),
    #[error("home directory not found")]
    HomeDirNotFound,
    #[error("crypto error: {0}")]
    Crypto(#[from] CryptoError),
}

pub type KeyStoreResult<T> = Result<T, KeyStoreError>;

pub use swiyu_core::KeyRole;

pub(crate) fn key_role_file_stem(role: KeyRole) -> &'static str {
    match role {
        KeyRole::Authorized => "authorized",
        KeyRole::Authentication => "authentication",
        KeyRole::Assertion => "assertion",
    }
}

/// Key pairs generated by [`KeyStore::generate`], held in memory until the full DID is known.
///
/// The caller uses the public key accessors to build the initial DID document, derives the
/// SCID, constructs the full DID, and then passes this value to [`KeyStore::commit`] to write
/// everything to disk.
#[derive(ZeroizeOnDrop)]
pub struct StagedKeys {
    authorized_signing: ed25519_dalek::SigningKey,
    #[zeroize(skip)]
    authorized_verifying: Ed25519VerifyingKey,
    authentication_signing: p256::ecdsa::SigningKey,
    #[zeroize(skip)]
    authentication_verifying: EcdsaVerifyingKey,
    assertion_signing: p256::ecdsa::SigningKey,
    #[zeroize(skip)]
    assertion_verifying: EcdsaVerifyingKey,
}

impl StagedKeys {
    /// Assembles `StagedKeys` from three signing keys; public keys are derived automatically.
    pub fn from_parts(
        authorized_signing: ed25519_dalek::SigningKey,
        authentication_signing: p256::ecdsa::SigningKey,
        assertion_signing: p256::ecdsa::SigningKey,
    ) -> Self {
        let authorized_verifying = authorized_signing.verifying_key();
        let authentication_verifying = *authentication_signing.verifying_key();
        let assertion_verifying = *assertion_signing.verifying_key();
        Self {
            authorized_signing,
            authorized_verifying,
            authentication_signing,
            authentication_verifying,
            assertion_signing,
            assertion_verifying,
        }
    }

    /// Signs `message` with the authorized EdDSA key and returns the 64-byte signature.
    pub fn sign_with_authorized(&self, message: &[u8]) -> [u8; 64] {
        use ed25519_dalek::Signer;
        self.authorized_signing.sign(message).to_bytes()
    }

    /// Raw 32-byte Ed25519 public key for the `authorized` role (signs DID log entries).
    pub fn authorized_key_bytes(&self) -> &[u8; 32] {
        self.authorized_verifying.as_bytes()
    }

    /// Uncompressed P-256 (x, y) coordinates of the `authentication` public key.
    pub fn authentication_key_coords(&self) -> ([u8; 32], [u8; 32]) {
        p256_coords(&self.authentication_verifying)
    }

    /// Uncompressed P-256 (x, y) coordinates of the `assertion` public key
    /// (signs verifiable credentials).
    pub fn assertion_key_coords(&self) -> ([u8; 32], [u8; 32]) {
        p256_coords(&self.assertion_verifying)
    }
}

/// A single entry returned by [`KeyStore::list`].
pub struct KeyStoreListEntry {
    /// The 12-character BLAKE3 hex prefix that identifies this entry on disk.
    pub hash: String,
    /// The full DID string read from `did.txt`.
    pub did: String,
}

/// A resolved key store entry for a single DID, returned by [`KeyStore::create`] and
/// [`KeyStore::lookup`].
///
/// Keys are loaded from disk on demand; constructing this type performs no I/O beyond what
/// the lookup itself already did.
#[derive(Debug)]
pub struct KeyStoreEntry {
    hash: String,
    did: String,
    entry_dir: PathBuf,
}

impl KeyStoreEntry {
    /// The 12-character BLAKE3 hex prefix that identifies this entry on disk.
    pub fn hash(&self) -> &str {
        &self.hash
    }

    /// The full DID string.
    pub fn did(&self) -> &str {
        &self.did
    }

    /// The highest snapshot version number present on disk (corresponds to the sequence number
    /// prefix of the `versionId` in the DID log).
    pub fn latest_version(&self) -> KeyStoreResult<u32> {
        std::fs::read_dir(&self.entry_dir)?
            .filter_map(|e| e.ok())
            .filter_map(|e| {
                let name = e.file_name();
                let s = name.to_string_lossy().into_owned();
                if s.len() == 4 && s.chars().all(|c| c.is_ascii_digit()) {
                    s.parse::<u32>().ok()
                } else {
                    None
                }
            })
            .max()
            .ok_or_else(|| KeyStoreError::NotFound(self.hash.clone()))
    }

    /// Returns the PEM content of the public key for `role` at `version` (latest if `None`).
    pub fn public_key_pem(&self, role: KeyRole, version: Option<u32>) -> KeyStoreResult<String> {
        let path = self.key_path(self.resolve_version(version)?, role, false);
        if !path.exists() {
            return Err(KeyStoreError::NotFound(self.hash.clone()));
        }
        Ok(std::fs::read_to_string(path)?)
    }

    /// Copies the public key for `role` at `version` (latest if `None`) to `dest` in PEM format.
    pub fn export_public_key(
        &self,
        role: KeyRole,
        version: Option<u32>,
        dest: &Path,
    ) -> KeyStoreResult<()> {
        let pem = self.public_key_pem(role, version)?;
        std::fs::write(dest, pem.as_bytes())?;
        Ok(())
    }

    /// Copies the private key for `role` at `version` (latest if `None`) to `dest` in PEM
    /// format. On Unix `dest` is created with mode 0600 (owner read/write only).
    pub fn export_private_key(
        &self,
        role: KeyRole,
        version: Option<u32>,
        dest: &Path,
    ) -> KeyStoreResult<()> {
        let path = self.key_path(self.resolve_version(version)?, role, true);
        if !path.exists() {
            return Err(KeyStoreError::NotFound(self.hash.clone()));
        }
        let pem = zeroize::Zeroizing::new(std::fs::read_to_string(path)?);
        crate::crypto::write_private_key_file(dest, pem.as_bytes())?;
        Ok(())
    }

    /// Loads the Ed25519 private signing key for `role` at `version` (latest if `None`).
    pub fn load_eddsa(
        &self,
        role: KeyRole,
        version: Option<u32>,
    ) -> KeyStoreResult<ed25519_dalek::SigningKey> {
        let path = self.key_path(self.resolve_version(version)?, role, true);
        if !path.exists() {
            return Err(KeyStoreError::NotFound(self.hash.clone()));
        }
        let pem = zeroize::Zeroizing::new(std::fs::read_to_string(path)?);
        Ok(crate::crypto::parse_private_key_eddsa(&pem)?)
    }

    /// Loads the P-256 ECDSA private signing key for `role` at `version` (latest if `None`).
    pub fn load_ecdsa(
        &self,
        role: KeyRole,
        version: Option<u32>,
    ) -> KeyStoreResult<p256::ecdsa::SigningKey> {
        let path = self.key_path(self.resolve_version(version)?, role, true);
        if !path.exists() {
            return Err(KeyStoreError::NotFound(self.hash.clone()));
        }
        let pem = zeroize::Zeroizing::new(std::fs::read_to_string(path)?);
        Ok(crate::crypto::parse_private_key_ecdsa(&pem)?)
    }

    /// Writes a new snapshot version with `staged` and returns its 1-based number.
    ///
    /// The next version is `latest_version() + 1`. Takes ownership of `staged` so the
    /// in-memory private keys are dropped immediately after the files are written.
    pub fn add_version(&self, staged: StagedKeys) -> KeyStoreResult<u32> {
        let next = self.latest_version()? + 1;
        let snapshot_dir = self.entry_dir.join(format!("{next:04}"));
        std::fs::create_dir_all(&snapshot_dir)?;

        write_private_key_eddsa(
            &staged.authorized_signing,
            &snapshot_dir.join("authorized-private.pem"),
        )?;
        write_public_key_eddsa(
            &staged.authorized_verifying,
            &snapshot_dir.join("authorized-public.pem"),
        )?;
        write_private_key_ecdsa(
            &staged.authentication_signing,
            &snapshot_dir.join("authentication-private.pem"),
        )?;
        write_public_key_ecdsa(
            &staged.authentication_verifying,
            &snapshot_dir.join("authentication-public.pem"),
        )?;
        write_private_key_ecdsa(
            &staged.assertion_signing,
            &snapshot_dir.join("assertion-private.pem"),
        )?;
        write_public_key_ecdsa(
            &staged.assertion_verifying,
            &snapshot_dir.join("assertion-public.pem"),
        )?;

        debug!("wrote new key store version: {}", snapshot_dir.display());
        Ok(next)
    }

    fn resolve_version(&self, version: Option<u32>) -> KeyStoreResult<u32> {
        match version {
            Some(v) => Ok(v),
            None => self.latest_version(),
        }
    }

    fn key_path(&self, version: u32, role: KeyRole, private: bool) -> PathBuf {
        let visibility = if private { "private" } else { "public" };
        self.entry_dir
            .join(format!("{version:04}"))
            .join(format!("{}-{visibility}.pem", key_role_file_stem(role)))
    }
}

/// Persists key pairs for generated DIDs on disk.
///
/// See `key-store.md` for the full directory layout and design rationale.
#[derive(Debug)]
pub struct KeyStore {
    root: PathBuf,
}

impl KeyStore {
    /// Opens an existing key store at `root`. Fails if the directory does not exist.
    pub fn open(root: &Path) -> KeyStoreResult<Self> {
        if !root.is_dir() {
            return Err(KeyStoreError::Io(std::io::Error::new(
                std::io::ErrorKind::NotFound,
                format!("key store directory '{}' does not exist", root.display()),
            )));
        }
        debug!("opened key store at {}", root.display());
        Ok(Self {
            root: root.to_path_buf(),
        })
    }

    /// Opens the key store at `root`, creating the root directory if it does not exist.
    pub fn open_or_create(root: &Path) -> KeyStoreResult<Self> {
        std::fs::create_dir_all(root)?;
        debug!("opened key store at {}", root.display());
        Ok(Self {
            root: root.to_path_buf(),
        })
    }

    /// Opens the default key store at `~/.didtool/keys`, creating it if necessary.
    pub fn open_default() -> KeyStoreResult<Self> {
        let root = home_dir()
            .ok_or(KeyStoreError::HomeDirNotFound)?
            .join(".didtool")
            .join("keys");
        debug!("resolved default key store path: {}", root.display());
        Self::open_or_create(&root)
    }

    /// Generates all three key pairs and returns them in memory as [`StagedKeys`].
    ///
    /// No filesystem I/O is performed. The caller uses the public keys from [`StagedKeys`]
    /// to build the initial DID document, derives the SCID, constructs the full DID, and
    /// then calls [`KeyStore::commit`] to write everything to disk.
    pub fn generate() -> KeyStoreResult<StagedKeys> {
        debug!("generating authorized Ed25519 key pair");
        let (authorized_signing, authorized_verifying) = generate_eddsa_key_pair();
        debug!("generating authentication P-256 key pair");
        let (authentication_signing, authentication_verifying) = generate_ecdsa_key_pair();
        debug!("generating assertion P-256 key pair");
        let (assertion_signing, assertion_verifying) = generate_ecdsa_key_pair();
        Ok(StagedKeys {
            authorized_signing,
            authorized_verifying,
            authentication_signing,
            authentication_verifying,
            assertion_signing,
            assertion_verifying,
        })
    }

    /// Writes the staged key pairs to disk for `did` and records `did.txt`.
    ///
    /// Takes ownership of `staged` so that the in-memory private keys are dropped
    /// immediately after the files are written.
    ///
    /// The keys are written into a `0001/` snapshot subdirectory under the entry directory
    /// derived from `did`. Fails with [`KeyStoreError::AlreadyExists`] if an entry for this
    /// DID already exists.
    pub fn commit(&self, staged: StagedKeys, did: &DID) -> KeyStoreResult<KeyStoreEntry> {
        let did_str = did.to_string();
        let hash = did_to_hash(&did_str);
        let entry_dir = self.root.join(&hash);

        if entry_dir.exists() {
            return Err(KeyStoreError::AlreadyExists(hash));
        }

        debug!("committing keys for DID '{}' (hash: {})", did_str, hash);
        let snapshot_dir = entry_dir.join("0001");
        std::fs::create_dir_all(&snapshot_dir)?;

        write_private_key_eddsa(
            &staged.authorized_signing,
            &snapshot_dir.join("authorized-private.pem"),
        )?;
        write_public_key_eddsa(
            &staged.authorized_verifying,
            &snapshot_dir.join("authorized-public.pem"),
        )?;
        write_private_key_ecdsa(
            &staged.authentication_signing,
            &snapshot_dir.join("authentication-private.pem"),
        )?;
        write_public_key_ecdsa(
            &staged.authentication_verifying,
            &snapshot_dir.join("authentication-public.pem"),
        )?;
        write_private_key_ecdsa(
            &staged.assertion_signing,
            &snapshot_dir.join("assertion-private.pem"),
        )?;
        write_public_key_ecdsa(
            &staged.assertion_verifying,
            &snapshot_dir.join("assertion-public.pem"),
        )?;

        std::fs::write(entry_dir.join("did.txt"), &did_str)?;
        debug!("wrote keys to {}", snapshot_dir.display());

        Ok(KeyStoreEntry {
            hash,
            did: did_str,
            entry_dir,
        })
    }

    /// Looks up the entry for `did`. Returns `Ok(None)` if no entry exists.
    ///
    /// Reads `did.txt` and verifies it matches `did` before returning the entry. Returns
    /// [`KeyStoreError::Mismatch`] if the subdirectory exists but `did.txt` holds a different
    /// DID (hash collision or corruption).
    pub fn lookup(&self, did: &DID) -> KeyStoreResult<Option<KeyStoreEntry>> {
        let did_str = did.to_string();
        let hash = did_to_hash(&did_str);
        debug!("looking up key store entry for DID '{}'", did_str);
        let entry_dir = self.root.join(&hash);

        if !entry_dir.exists() {
            return Ok(None);
        }

        let stored = std::fs::read_to_string(entry_dir.join("did.txt"))?
            .trim()
            .to_string();
        if stored != did_str {
            return Err(KeyStoreError::Mismatch(hash));
        }

        Ok(Some(KeyStoreEntry {
            hash,
            did: did_str,
            entry_dir,
        }))
    }

    /// Looks up the entry by its 12-character BLAKE3 hash. Returns `Ok(None)` if no entry
    /// exists.
    pub fn lookup_by_hash(&self, hash: &str) -> KeyStoreResult<Option<KeyStoreEntry>> {
        debug!("looking up key store entry by hash '{}'", hash);
        let entry_dir = self.root.join(hash);

        if !entry_dir.exists() {
            return Ok(None);
        }

        let did = std::fs::read_to_string(entry_dir.join("did.txt"))?
            .trim()
            .to_string();
        Ok(Some(KeyStoreEntry {
            hash: hash.to_string(),
            did,
            entry_dir,
        }))
    }

    /// Removes the entry for `did` and all its contents.
    ///
    /// Fails with [`KeyStoreError::NotFound`] if no entry exists.
    pub fn remove(&self, did: &DID) -> KeyStoreResult<()> {
        let hash = did_to_hash(&did.to_string());
        let entry_dir = self.root.join(&hash);

        if !entry_dir.exists() {
            return Err(KeyStoreError::NotFound(hash));
        }

        std::fs::remove_dir_all(entry_dir)?;
        Ok(())
    }

    /// Returns `true` if an entry for `did` exists in the key store.
    pub fn exists(&self, did: &DID) -> bool {
        self.root.join(did_to_hash(&did.to_string())).exists()
    }

    /// Returns all entries in the key store, sorted by hash.
    ///
    /// A single user manages at most a few dozen DIDs, so loading the full list into memory is
    /// negligible. Returning a sorted `Vec` keeps the API simple and gives callers a stable,
    /// predictable order without requiring them to collect and sort an iterator themselves.
    pub fn list(&self) -> KeyStoreResult<Vec<KeyStoreListEntry>> {
        let mut entries: Vec<KeyStoreListEntry> = std::fs::read_dir(&self.root)?
            .filter_map(|e| e.ok())
            .filter_map(|e| {
                if !e.path().is_dir() {
                    return None;
                }
                let hash = e.file_name().to_string_lossy().into_owned();
                let did = std::fs::read_to_string(e.path().join("did.txt"))
                    .ok()?
                    .trim()
                    .to_string();
                Some(KeyStoreListEntry { hash, did })
            })
            .collect();
        entries.sort_by(|a, b| a.hash.cmp(&b.hash));
        Ok(entries)
    }
}

/// Returns the 12-character BLAKE3 hex prefix used as the on-disk subdirectory name for `did`.
fn did_to_hash(did: &str) -> String {
    let hash = blake3::hash(did.as_bytes());
    let hex = hash.to_hex();
    hex[..12].to_string()
}

fn home_dir() -> Option<PathBuf> {
    dirs::home_dir()
}

fn p256_coords(key: &EcdsaVerifyingKey) -> ([u8; 32], [u8; 32]) {
    let point = key.to_encoded_point(false);
    let x: [u8; 32] = (*point.x().expect("uncompressed point has x")).into();
    let y: [u8; 32] = (*point.y().expect("uncompressed point has y")).into();
    (x, y)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_did() -> DID {
        DID::parse("did:webvh:abc123:example.com").unwrap()
    }

    fn temp_store() -> (tempfile::TempDir, KeyStore) {
        let dir = tempfile::tempdir().unwrap();
        let store = KeyStore::open_or_create(dir.path()).unwrap();
        (dir, store)
    }

    #[test]
    fn open_nonexistent_fails() {
        assert!(matches!(
            KeyStore::open(Path::new("/nonexistent/path/xyz")).unwrap_err(),
            KeyStoreError::Io(_)
        ));
    }

    #[test]
    fn open_or_create_creates_directory() {
        let dir = tempfile::tempdir().unwrap();
        let new_path = dir.path().join("keystore");
        KeyStore::open_or_create(&new_path).unwrap();
        assert!(new_path.is_dir());
    }

    #[test]
    fn commit_writes_expected_files() {
        let (_dir, store) = temp_store();
        let entry = store
            .commit(KeyStore::generate().unwrap(), &test_did())
            .unwrap();
        let snapshot = store.root.join(entry.hash()).join("0001");
        assert!(snapshot.join("authorized-private.pem").exists());
        assert!(snapshot.join("authorized-public.pem").exists());
        assert!(snapshot.join("authentication-private.pem").exists());
        assert!(snapshot.join("authentication-public.pem").exists());
        assert!(snapshot.join("assertion-private.pem").exists());
        assert!(snapshot.join("assertion-public.pem").exists());
        assert!(store.root.join(entry.hash()).join("did.txt").exists());
    }

    #[test]
    fn commit_twice_fails() {
        let (_dir, store) = temp_store();
        store
            .commit(KeyStore::generate().unwrap(), &test_did())
            .unwrap();
        assert!(matches!(
            store
                .commit(KeyStore::generate().unwrap(), &test_did())
                .unwrap_err(),
            KeyStoreError::AlreadyExists(_)
        ));
    }

    #[test]
    fn lookup_returns_none_for_unknown_did() {
        let (_dir, store) = temp_store();
        assert!(store.lookup(&test_did()).unwrap().is_none());
    }

    #[test]
    fn lookup_returns_entry_after_create() {
        let (_dir, store) = temp_store();
        store
            .commit(KeyStore::generate().unwrap(), &test_did())
            .unwrap();
        let entry = store.lookup(&test_did()).unwrap().unwrap();
        assert_eq!(entry.did(), test_did().to_string());
    }

    #[test]
    fn lookup_by_hash_returns_entry() {
        let (_dir, store) = temp_store();
        let created = store
            .commit(KeyStore::generate().unwrap(), &test_did())
            .unwrap();
        let found = store.lookup_by_hash(created.hash()).unwrap().unwrap();
        assert_eq!(found.did(), test_did().to_string());
        assert_eq!(found.hash(), created.hash());
    }

    #[test]
    fn lookup_by_hash_returns_none_for_unknown_hash() {
        let (_dir, store) = temp_store();
        assert!(store.lookup_by_hash("000000000000").unwrap().is_none());
    }

    #[test]
    fn exists_returns_false_before_create() {
        let (_dir, store) = temp_store();
        assert!(!store.exists(&test_did()));
    }

    #[test]
    fn exists_returns_true_after_create() {
        let (_dir, store) = temp_store();
        store
            .commit(KeyStore::generate().unwrap(), &test_did())
            .unwrap();
        assert!(store.exists(&test_did()));
    }

    #[test]
    fn remove_deletes_entry() {
        let (_dir, store) = temp_store();
        store
            .commit(KeyStore::generate().unwrap(), &test_did())
            .unwrap();
        store.remove(&test_did()).unwrap();
        assert!(!store.exists(&test_did()));
    }

    #[test]
    fn remove_nonexistent_fails() {
        let (_dir, store) = temp_store();
        assert!(matches!(
            store.remove(&test_did()).unwrap_err(),
            KeyStoreError::NotFound(_)
        ));
    }

    #[test]
    fn list_returns_sorted_entries() {
        let (_dir, store) = temp_store();
        let did1 = DID::parse("did:webvh:abc123:example.com").unwrap();
        let did2 = DID::parse("did:webvh:def456:other.example.com").unwrap();
        store.commit(KeyStore::generate().unwrap(), &did1).unwrap();
        store.commit(KeyStore::generate().unwrap(), &did2).unwrap();
        let entries = store.list().unwrap();
        assert_eq!(entries.len(), 2);
        assert!(entries[0].hash <= entries[1].hash);
        let dids: Vec<&str> = entries.iter().map(|e| e.did.as_str()).collect();
        assert!(dids.contains(&"did:webvh:abc123:example.com"));
        assert!(dids.contains(&"did:webvh:def456:other.example.com"));
    }

    #[test]
    fn latest_version_is_one_after_create() {
        let (_dir, store) = temp_store();
        let entry = store
            .commit(KeyStore::generate().unwrap(), &test_did())
            .unwrap();
        assert_eq!(entry.latest_version().unwrap(), 1);
    }

    #[test]
    fn public_key_pem_contains_public_key_header() {
        let (_dir, store) = temp_store();
        let entry = store
            .commit(KeyStore::generate().unwrap(), &test_did())
            .unwrap();
        for role in [
            KeyRole::Authorized,
            KeyRole::Authentication,
            KeyRole::Assertion,
        ] {
            let pem = entry.public_key_pem(role, None).unwrap();
            assert!(
                pem.contains("PUBLIC KEY"),
                "expected PUBLIC KEY header for {role:?}"
            );
        }
    }

    #[test]
    fn export_public_key_writes_pem_file() {
        let (dir, store) = temp_store();
        let entry = store
            .commit(KeyStore::generate().unwrap(), &test_did())
            .unwrap();
        let dest = dir.path().join("exported-public.pem");
        entry
            .export_public_key(KeyRole::Authorized, None, &dest)
            .unwrap();
        assert!(
            std::fs::read_to_string(&dest)
                .unwrap()
                .contains("PUBLIC KEY")
        );
    }

    #[test]
    fn export_private_key_writes_pem_file() {
        let (dir, store) = temp_store();
        let entry = store
            .commit(KeyStore::generate().unwrap(), &test_did())
            .unwrap();
        let dest = dir.path().join("exported-private.pem");
        entry
            .export_private_key(KeyRole::Authorized, None, &dest)
            .unwrap();
        assert!(
            std::fs::read_to_string(&dest)
                .unwrap()
                .contains("PRIVATE KEY")
        );
    }

    #[test]
    #[cfg(unix)]
    fn export_private_key_has_restricted_permissions() {
        use std::os::unix::fs::PermissionsExt;
        let (dir, store) = temp_store();
        let entry = store
            .commit(KeyStore::generate().unwrap(), &test_did())
            .unwrap();
        let dest = dir.path().join("exported-private-perms.pem");
        entry
            .export_private_key(KeyRole::Authorized, None, &dest)
            .unwrap();
        let mode = std::fs::metadata(&dest).unwrap().permissions().mode();
        assert_eq!(mode & 0o777, 0o600);
    }

    #[test]
    fn did_hash_is_twelve_lowercase_hex_chars() {
        let hash = did_to_hash("did:webvh:abc123:example.com");
        assert_eq!(hash.len(), 12);
        assert!(hash.chars().all(|c| c.is_ascii_hexdigit()));
    }
}
